In [1]:
import sys
import os
print(os.getcwd())
os.chdir("C:\\Users\\Samuel\\Dropbox\\Git Projects\\glo-7030-projet")
print(os.getcwd())

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
sys.path.append("../..")

from src.mapping.utils import warpPerspective, crop_center
from src.semantic.utils.utils import readfile

rink_2d_label = readfile('data/rink/rink_label')
rink_2d = crop_center(rink_2d_label, 450, 256)

semseg = readfile("data/train/image-104")
semseg = crop_center(semseg, 450, 256)

from src.semantic.net_parameters import p_classes_color
import matplotlib as mpl
import matplotlib.pyplot as plt
cmap = mpl.colors.ListedColormap(p_classes_color)

#'ice': 1, 'board': 2, 'circlezone': 3, 'circlemid': 4, 'goal': 5, 'blue': 6, 'red': 7, 'fo': 8

plt.subplot(1,2,1)
plt.imshow(semseg,cmap=cmap)
plt.subplot(1,2,2)
plt.imshow(rink_2d,cmap=cmap)

C:\Users\Samuel\Dropbox\Git Projects\glo-7030-projet\src\mapping
C:\Users\Samuel\Dropbox\Git Projects\glo-7030-projet


In [26]:
h = np.array([[1,0,0],[0,1,0],[0,0,1]])
proj= warpPerspective(semseg, h)
print(h)
print(proj[225,128])

[[1 0 0]
 [0 1 0]
 [0 0 1]]
1.0


In [27]:
# loss zone-face-offs
x3 = np.array([[75],[375]])
y3 = np.array([[70],[180]])
p3 = np.where(proj==3)

dx3 = np.amin((p3[0] - x3)**2, axis=0)
dy3 = np.amin((p3[1] - y3)**2, axis=0)
np.sum(dx3+dy3)/max(1,len(p3[0]))


0.0

In [28]:
# loss blue-face-offs -- basically the same
x8 = np.array([[170],[280]])
y8 = np.array([[70],[180]])
p8 = np.where(proj == 8)

dx8 = np.amin((p8[0] - x8)**2, axis=0)
dy8 = np.amin((p8[1] - y8)**2, axis=0)
np.sum(dx8+dy8)/max(1,len(p8[0]))

17319.321976149913

In [34]:
# loss blue-line -- on x only
x6 = np.array([[158],[292]])
p6 = np.where(proj == 6)

dx6 = np.amin((p6[0] - x6)**2, axis=0)
np.sum(dx6)/max(1,len(p6[0]))

1671.336909018673